# Generated by Django 3.2.1 on 2021-05-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
